/**
 * @file    dotenv.c
 * @brief   Embedded .env parser implementation.
 *
 * Parses KEY=VALUE lines from an objcopy-embedded binary blob.
 * The blob is stored in read-only flash (rodata section); parsing happens
 * once at startup into a fixed-size static table.
 */

#include "dotenv.h"

#include <stdlib.h>
#include <string.h>
#include "esp_log.h"

static const char *TAG = "dotenv";

/**
 * @brief   Embedded blob symbols generated by objcopy at build time.
 *
 * objcopy names are derived from the file path by replacing
 * non-alphanumeric characters with underscores:
 *
 *     ".env"  ->  \c _binary__env_start  /  \c _binary__env_end
 *             (double underscore from the leading dot)
 */

extern const unsigned char _binary__env_start[] asm("_binary__env_start");
extern const unsigned char _binary__env_end[]   asm("_binary__env_end");

/** @test{dotenv_parse_line} Fed directly by test_dotenv.c. */

/* ── Limits ──────────────────────────────────────────────────── */

#define DOTENV_MAX_KEYS  16    /**< Maximum storable key/value pairs */
#define DOTENV_KEY_LEN   32    /**< Maximum key length (bytes, excl. NUL) */
#define DOTENV_VAL_LEN   64    /**< Maximum value length (bytes, excl. NUL) */

/** Single parsed entry: key and value as fixed-size char arrays. */
typedef struct {
    char key[DOTENV_KEY_LEN];
    char val[DOTENV_VAL_LEN];
} dotenv_entry_t;

static dotenv_entry_t s_entries[DOTENV_MAX_KEYS]; /**< Parsed entry table */
static int            s_entry_count;              /**< Number of valid entries */

/* ── Internal helpers ─────────────────────────────────────────── */

/**
 * @brief Parse a single "KEY=VALUE" line into the static table.
 *
 * Handles:
 *  - Optional double-quote wrapping on values  (VAL="hello")
 *  - Trailing spaces and carriage-return
 *  - Empty keys and over-long keys/values are silently dropped.
 *
 * @param line  Pointer to first non-whitespace character.
 * @param len   Number of bytes until end-of-line (excluding the terminator).
 */
void dotenv_parse_line(const char *line, size_t len)
{
    const char *eq = memchr(line, '=', len);
    if (!eq) return;

    size_t key_len = eq - line;
    while (key_len > 0 && line[key_len - 1] == ' ') key_len--;

    const char *val = eq + 1;
    size_t val_len = len - (size_t)(val - line);
    while (val_len > 0 && *val == ' ') { val++; val_len--; }

    if (val_len >= 2 && val[0] == '"' && val[val_len - 1] == '"') {
        val++;
        val_len -= 2;
    }

    while (val_len > 0 && val[val_len - 1] == ' ')  val_len--;
    while (val_len > 0 && val[val_len - 1] == '\r') val_len--;

    if (key_len == 0 || key_len >= DOTENV_KEY_LEN) return;
    if (val_len >= DOTENV_VAL_LEN) return;
    if (s_entry_count >= DOTENV_MAX_KEYS) return;

    memcpy(s_entries[s_entry_count].key, line, key_len);
    s_entries[s_entry_count].key[key_len] = '\0';
    memcpy(s_entries[s_entry_count].val, val, val_len);
    s_entries[s_entry_count].val[val_len] = '\0';
    s_entry_count++;
}

/* ── Public API ───────────────────────────────────────────────── */

void dotenv_init(void)
{
    const unsigned char *p   = _binary__env_start;
    const unsigned char *end = _binary__env_end;

    ESP_LOGI(TAG, "Loading embedded .env (%d bytes)", (int)(end - p));

    /*
     * Walk the blob byte-by-byte.
     * Lines end at '\n' or '\0'; the *last* line is handled after the loop.
     * Leading whitespace is stripped per-line; '#' lines are skipped.
     */

    const unsigned char *line_start = p;

    for (; p < end; p++) {
        if (*p == '\n' || *p == '\0') {
            const unsigned char *ls = line_start;
            while (ls < p && (*ls == ' ' || *ls == '\t')) ls++;
            size_t len = (size_t)(p - ls);
            if (len > 0 && *ls != '#') {
                dotenv_parse_line((const char *)ls, len);
            }
            line_start = p + 1;
            if (*p == '\0') break;
        }
    }

    /* Handle the final line (no trailing newline / NUL at EOF) */
    if (line_start < end) {
        const unsigned char *ls = line_start;
        while (ls < end && (*ls == ' ' || *ls == '\t')) ls++;
        size_t len = (size_t)(end - ls);
        if (len > 0 && *ls != '#') {
            dotenv_parse_line((const char *)ls, len);
        }
    }

    ESP_LOGI(TAG, "Parsed %d entries", s_entry_count);
}

const char *dotenv_get(const char *key)
{
    for (int i = 0; i < s_entry_count; i++) {
        if (strcmp(s_entries[i].key, key) == 0)
            return s_entries[i].val;
    }
    return NULL;
}

int dotenv_get_int(const char *key, int default_value)
{
    const char *val = dotenv_get(key);
    if (!val) return default_value;
    return atoi(val);
}

void dotenv_reset(void)
{
    s_entry_count = 0;
    memset(s_entries, 0, sizeof(s_entries));
}
