/**
 * @file    web_API.c
 * @brief   HTTP endpoint handlers — implementation.
 *
 * Two handler families:
 *   static_handler  — serves embedded files (HTML, CSS, JS) from flash.
 *   status_handler  — builds a cJSON object with chip info, memory, Wi-Fi
 *                     state, firmware metadata, and sends it as JSON.
 *
 * Embedded files are linked via objcopy-generated symbols
 * (\c _binary_\<name\>_start / \c _binary_\<name\>_end) declared here as extern.
 *
 * @note    esp_clk_cpu_freq() is pulled from esp_private/esp_clk.h because
 *          no public equivalent exists in ESP-IDF v6.0.2 for the *actual*
 *          running CPU frequency (as opposed to the configured Kconfig value).
 */

#include "web_API.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cJSON.h"
#include "dotenv.h"
#include "esp_app_desc.h"
#include "esp_chip_info.h"
#include "esp_err.h"
#include "esp_flash.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "esp_mac.h"
#include "esp_private/esp_clk.h"   /* esp_clk_cpu_freq() — private API, see note */
#include "esp_system.h"
#include "esp_timer.h"
#include "freertos/task.h"
#include "mbedtls/constant_time.h"
#include "wifi_connect.h"
#include "wol.h"

static const char *TAG = "web_API";

#define API_KEY_HEADER       "X-API-Key"
#define MAX_API_KEY_LEN      96
#define MIN_SAFE_HEAP_BYTES  30000

/* ── Embedded file symbols (generated by EMBED_FILES in CMakeLists.txt) ── */

extern const uint8_t index_html_start[] asm("_binary_index_html_start");
extern const uint8_t index_html_end[]   asm("_binary_index_html_end");
extern const uint8_t style_css_start[]  asm("_binary_style_css_start");
extern const uint8_t style_css_end[]    asm("_binary_style_css_end");
extern const uint8_t app_js_start[]     asm("_binary_app_js_start");
extern const uint8_t app_js_end[]       asm("_binary_app_js_end");
extern const uint8_t uplot_js_start[]   asm("_binary_uplot_min_js_start");
extern const uint8_t uplot_js_end[]     asm("_binary_uplot_min_js_end");
extern const uint8_t uplot_css_start[]  asm("_binary_uplot_min_css_start");
extern const uint8_t uplot_css_end[]    asm("_binary_uplot_min_css_end");

/* ── Static file table ────────────────────────────────────────── */

/** Describes one embedded file: URI, Content-Type, and flash bounds. */
typedef struct {
    const char    *uri;          /**< Request path (e.g. "/style.css") */
    const char    *content_type; /**< HTTP Content-Type header value   */
    const uint8_t *start;        /**< Pointer to first byte in flash   */
    const uint8_t *end;          /**< Pointer past last byte in flash  */
} embedded_file_t;

/**
 * Lookup table for the wildcard handler.
 *
 * `/` and `/index.html` both serve the same blob. The table is static const
 * so it lives in flash alongside the file data.
 */
static const embedded_file_t s_files[] = {
    {"/",             "text/html",              index_html_start, index_html_end},
    {"/index.html",   "text/html",              index_html_start, index_html_end},
    {"/style.css",    "text/css",               style_css_start,  style_css_end},
    {"/app.js",       "application/javascript", app_js_start,     app_js_end},
    {"/uplot.min.js", "application/javascript", uplot_js_start,   uplot_js_end},
    {"/uplot.min.css","text/css",               uplot_css_start,  uplot_css_end},
};

/**
 * @brief Enforce low-memory request rejection to protect heap stability.
 */
static bool heap_is_safe_or_reject(httpd_req_t *req)
{
    if (esp_get_free_heap_size() >= MIN_SAFE_HEAP_BYTES) {
        return true;
    }

    httpd_resp_set_status(req, "503 Service Unavailable");
    httpd_resp_sendstr(req, "Low memory threshold reached");
    return false;
}

/**
 * @brief Validate X-API-Key via constant-time compare and reject on failure.
 */
static bool api_auth_or_reject(httpd_req_t *req)
{
    const char *expected_token = dotenv_get("WEB_API_TOKEN");
    if (!expected_token || expected_token[0] == '\0') {
        ESP_LOGE(TAG, "WEB_API_TOKEN not configured");
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR,
                            "API auth is not configured");
        return false;
    }

    size_t expected_len = strlen(expected_token);
    if (expected_len == 0 || expected_len >= MAX_API_KEY_LEN) {
        ESP_LOGE(TAG, "WEB_API_TOKEN length is invalid");
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR,
                            "API auth config is invalid");
        return false;
    }

    size_t header_len = httpd_req_get_hdr_value_len(req, API_KEY_HEADER);
    if (header_len != expected_len) {
        httpd_resp_send_err(req, HTTPD_401_UNAUTHORIZED, "Unauthorized");
        return false;
    }

    char header_val[MAX_API_KEY_LEN] = {0};
    if (httpd_req_get_hdr_value_str(req, API_KEY_HEADER,
                                    header_val, sizeof(header_val)) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_401_UNAUTHORIZED, "Unauthorized");
        return false;
    }

    if (mbedtls_ct_memcmp(header_val, expected_token, expected_len) != 0) {
        httpd_resp_send_err(req, HTTPD_401_UNAUTHORIZED, "Unauthorized");
        return false;
    }

    return true;
}

/* ── Handlers ─────────────────────────────────────────────────── */

/**
 * @brief Serve an embedded static file matched by request URI.
 *
 * Iterates s_files[] linearly (6 entries — negligible cost). Returns 404
 * if the URI is not in the table.
 */
static esp_err_t static_handler(httpd_req_t *req)
{
    for (size_t i = 0; i < sizeof(s_files) / sizeof(s_files[0]); i++) {
        if (strcmp(req->uri, s_files[i].uri) != 0) continue;

        size_t len = (size_t)(s_files[i].end - s_files[i].start);
        httpd_resp_set_type(req, s_files[i].content_type);
        httpd_resp_send(req, (const char *)s_files[i].start, len);
        return ESP_OK;
    }

    httpd_resp_send_404(req);
    return ESP_FAIL;
}

/**
 * @brief Map esp_chip_model_t enum to a human-readable string.
 */
const char *chip_model_str(esp_chip_model_t model)
{
    switch (model) {
    case CHIP_ESP32:   return "ESP32";
    case CHIP_ESP32S2: return "ESP32-S2";
    case CHIP_ESP32S3: return "ESP32-S3";
    case CHIP_ESP32C3: return "ESP32-C3";
    case CHIP_ESP32C2: return "ESP32-C2";
    case CHIP_ESP32C6: return "ESP32-C6";
    case CHIP_ESP32H2: return "ESP32-H2";
    case CHIP_ESP32P4: return "ESP32-P4";
    case CHIP_ESP32C5: return "ESP32-C5";
    default:           return "Unknown";
    }
}

/**
 * @brief Build and send a /api/status JSON response.
 *
 * Gathers:
 *  - Network:    Wi-Fi health, LAN IP, MAC address.
 *  - Memory:     heap free/total/min, free stack, task count, uptime.
 *  - Device:     chip model, cores, revision, CPU freq, flash size, features.
 *  - Firmware:   app name, version, build date/time.
 *
 * All values are read on every request — nothing is cached.
 */
static esp_err_t status_handler(httpd_req_t *req)
{
    if (!api_auth_or_reject(req)) {
        return ESP_FAIL;
    }
    if (!heap_is_safe_or_reject(req)) {
        return ESP_FAIL;
    }

    const char *lan_ip = get_LAN_ip();

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        httpd_resp_send_500(req);
        return ESP_FAIL;
    }

    cJSON_AddBoolToObject(root,   "wifi",   wifi_health());
    cJSON_AddStringToObject(root, "ip",     lan_ip ? lan_ip : "");

    cJSON_AddNumberToObject(root, "heap_free",     esp_get_free_heap_size());
    cJSON_AddNumberToObject(root, "heap_min_free", esp_get_minimum_free_heap_size());
    cJSON_AddNumberToObject(root, "heap_total",    heap_caps_get_total_size(MALLOC_CAP_8BIT));

    cJSON_AddNumberToObject(root, "free_stack", uxTaskGetStackHighWaterMark(NULL));
    cJSON_AddNumberToObject(root, "task_count", uxTaskGetNumberOfTasks());
    cJSON_AddNumberToObject(root, "uptime",     (double)(esp_timer_get_time() / 1000000ULL));

    esp_chip_info_t chip_info;
    esp_chip_info(&chip_info);

    cJSON *features = cJSON_CreateArray();
    if (chip_info.features & CHIP_FEATURE_EMB_FLASH)  cJSON_AddItemToArray(features, cJSON_CreateString("Embedded Flash"));
    if (chip_info.features & CHIP_FEATURE_WIFI_BGN)   cJSON_AddItemToArray(features, cJSON_CreateString("Wi-Fi b/g/n"));
    if (chip_info.features & CHIP_FEATURE_BT)         cJSON_AddItemToArray(features, cJSON_CreateString("BT"));
    if (chip_info.features & CHIP_FEATURE_BLE)        cJSON_AddItemToArray(features, cJSON_CreateString("BLE"));
    if (chip_info.features & CHIP_FEATURE_IEEE802154) cJSON_AddItemToArray(features, cJSON_CreateString("802.15.4"));
    cJSON_AddItemToObject(root, "chip_features", features);

    cJSON_AddStringToObject(root, "chip_model",    chip_model_str(chip_info.model));
    cJSON_AddNumberToObject(root, "chip_cores",    chip_info.cores);
    cJSON_AddNumberToObject(root, "chip_revision", chip_info.revision);
    cJSON_AddNumberToObject(root, "cpu_freq",      esp_clk_cpu_freq());

    const esp_app_desc_t *app_info = esp_app_get_description();
    if (app_info) {
        cJSON_AddStringToObject(root, "app_name",    app_info->project_name);
        cJSON_AddStringToObject(root, "app_version", app_info->version);
        cJSON_AddStringToObject(root, "app_date",    app_info->date);
        cJSON_AddStringToObject(root, "app_time",    app_info->time);
    }

    uint32_t flash_size = 0;
    if (esp_flash_get_size(NULL, &flash_size) == ESP_OK) {
        cJSON_AddNumberToObject(root, "flash_size", flash_size);
    }

    uint8_t mac[6];
    if (esp_read_mac(mac, ESP_MAC_WIFI_STA) == ESP_OK) {
        char mac_str[18];
        snprintf(mac_str, sizeof(mac_str),
                 "%02X:%02X:%02X:%02X:%02X:%02X",
                 mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
        cJSON_AddStringToObject(root, "mac", mac_str);
    }

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);

    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json_str, strlen(json_str));

    free(json_str);
    return ESP_OK;
}

/**
 * @brief Trigger a WoL send and return JSON status.
 */
static esp_err_t wol_handler(httpd_req_t *req)
{
    if (!api_auth_or_reject(req)) {
        return ESP_FAIL;
    }
    if (!heap_is_safe_or_reject(req)) {
        return ESP_FAIL;
    }

    esp_err_t ret = wol_send();
    httpd_resp_set_type(req, "application/json");

    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "wol_send failed: %s", esp_err_to_name(ret));
        httpd_resp_set_status(req, "500 Internal Server Error");
        httpd_resp_sendstr(req, "{\"ok\":false}");
        return ESP_FAIL;
    }

    httpd_resp_sendstr(req, "{\"ok\":true}");
    return ESP_OK;
}

/* ── Registration ─────────────────────────────────────────────── */

/**
 * @brief Register all URI handlers.
 *
 * Order is significant with wildcard matching:
 *   1. /api/status  — exact JSON endpoint.
 *   2. /api/wol     — exact endpoint to send WoL packet.
 *   3. /            — exact root → index.html.
 *   4. \/\*         — wildcard catch-all → static file table.
 *
 * If '\/\*' were registered before `/api/status`, the wildcard would
 * intercept it because '\/\*' matches anything starting with `/`.
 */
void web_API_init(httpd_handle_t server)
{
    httpd_uri_t status_uri = {
        .uri     = "/api/status",
        .method  = HTTP_GET,
        .handler = status_handler,
    };
    httpd_register_uri_handler(server, &status_uri);

    httpd_uri_t wol_uri = {
        .uri     = "/api/wol",
        .method  = HTTP_POST,
        .handler = wol_handler,
    };
    httpd_register_uri_handler(server, &wol_uri);

    httpd_uri_t wol_get_uri = {
        .uri     = "/api/wol",
        .method  = HTTP_GET,
        .handler = wol_handler,
    };
    httpd_register_uri_handler(server, &wol_get_uri);

    httpd_uri_t root_uri = {
        .uri     = "/",
        .method  = HTTP_GET,
        .handler = static_handler,
    };
    httpd_register_uri_handler(server, &root_uri);

    httpd_uri_t wildcard = {
        .uri     = "/*",
        .method  = HTTP_GET,
        .handler = static_handler,
    };
    httpd_register_uri_handler(server, &wildcard);

    ESP_LOGI(TAG, "Endpoints registered");
}
